.TH DUPLICATES 1 "v\ 1.0.2" "2014-05-15" "GNU"
.SH NAME
.B duplicates
\- Generate a list of duplicated files in user input dir.
.SH SYNOPSIS
duplicates \fIdir [dir ...]\fR > \fIdups.lst\fR
.br
duplicates \fIdir [dir ...]\fR > \fIdups.lst\fR 2> \fIbroken_links\fR
.br
.SH OPTIONS
.TP
\-h, prints a brief help message.
.TP
\-d, don't delete the workfiles in\fI/tmp\fR
.TP
\-v, each invocation increases verbosity, default is 0.
.br
.RS
0, emit no progress information.
.br
1, emit information of each new section started.
.br
2, emit pathname of each 100th file during Md5sum generation.
.br
3, the same for every tenth file.
.br
4+, the same for every file.
.RE
.br
You probably do not want to use this option when you are redirecting
.br
\fIstderr\fR to a file. Eg 2> \fIerrors_file\fR
.SH DESCRIPTION
When run to conclusion a total of 8 workfiles will be created in /tmp.
.br
The filenames are of the form \fI$USERduplicates0\fR .. \fI$USERduplicates7\fR
.br
The program works by sorting md5sum, inode number, then pathname of
.br
every regular file and symlink under the named directory.
.br
Then the sorted file is traversed and only those records that match on
.br
md5sum but differ in inode number are preserved.
.br
Because symlinks are statted the recorded inode is that of the target
.br
not the actual symlink itself.
.br
This ordering is not too useful for dealing with the actual duplicated
.br
files, especially when the duplication has arisen from recursive
.br
copying of directories. Consequently I sort the results by group, based
.br
on the most signifcant part of the path name of the first item of the
.br
replicated group. This result is sent to \fIstdout.\fR
.br
Errors where they occur are sent to \fIstderr\fR as also is the result of
.br
of selecting any level of verbosity.
.br
NB zero length files are never taken into account in this program.
.br
.SH VERSION
This documentation describes \fBduplicates\fR version 1.0.2
.SH "SEE ALSO"
bigfiles(1), brokensym(1), oldfiles(1), processdups(1), zapfiles(1),
cleanuputils(7)
.br
